### ISSUE TITLE
Certain key positions corrupt the layout (are duplicated when the layout link is opened.

### ISSUE THREAD

**Issue by Intuos5** [cyanophage/cyanophage.github.io#2]
I have been using your tool a lot to create new keyboard layouts, but I noticed that certain keypositions can corrupt the link for a layout. For example, this layout:
![image](https://github.com/cyanophage/cyanophage.github.io/assets/63149655/8639fe61-6d3a-48ca-8e80-86dfb13b8f13)
Changes to this layout when the link is opened or the tab is duplicated.
![image](https://github.com/cyanophage/cyanophage.github.io/assets/63149655/b3b6e738-81d8-4307-a4fe-18bf94ec801a)
Notice there are two A's now.
Here is the link to the layout: https://cyanophage.github.io/playground.html?layout=qwdf%5C%27kgu%2F-nrtsbmhoaibackpjcvxzl%2C.y&mode=ergo

**Comment by cyanophage** [comment]
This is caused by the way that the layout is updated into the url. If you move the tab key it inserts the word "tab" into the string for the layout. To make it so that you could put any key anywhere and have that be a shareable layout then I'd have to change the way the string in the url worked. For the moment I made it so you can't move those keys that would cause this problem. Later I'll think of a better fix.

**Comment by Intuos5** [comment]
@cyanophage thanks for the quick fixes! Could you list the keys for me here (or mark them with an annotation tool of choice)? 
That way, I'll be able to correct the 9 layouts I have open to check with custom effort weights, to make sure I don't have to redo them.
